services:
  app:
    build:
      context: .
      dockerfile: Dockerfile/php/Dockerfile
    image: dummy-api-app
    container_name: dummy-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_NAME: "${APP_NAME:-Laravel}"
      APP_ENV: "${APP_ENV:-local}"
      APP_KEY: "${APP_KEY:-}"
      APP_DEBUG: "${APP_DEBUG:-true}"
      APP_URL: "${APP_URL:-http://localhost:8000}"
      DB_CONNECTION: "${DB_CONNECTION:-mysql}"
      DB_HOST: mysql-db
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE:-mituni_api}"
      DB_USERNAME: "${DB_USERNAME:-myuser}"
      DB_PASSWORD: "${DB_PASSWORD:-mypass}"
      REDIS_HOST: redis
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - set-docker-server-roby_backend

networks:
  set-docker-server-roby_backend:
    external: true
